### ISSUE TITLE
گالری تصاویر

### ISSUE THREAD

**Issue by mehrdad2** [negareh/Kimial#6]
در صفحه گالری تصاویر از عکس های مقاطع موجود در کاتالوگ استفاده گردد

**Comment by shimafaraji** [comment]
تصویر مقاطع در صفحه محصولات استفاده شدند برای این صفحه از تصاویر کاتالوگ استفاده شد
اگر تمایل دارند تصاویر پروژه های شرکت را ارسال کنند
